### ISSUE TITLE
TM UI: Create and add icon for header

### ISSUE THREAD

**Issue by jessbeutler** [publicdomainmap/tasking-manager#4]
- [ ] Create logo
- [ ] Upload
- [ ] Add to code

**Comment by jessbeutler** [comment]
Temporary suggestion until we get a proper logo designed: 
![image](https://user-images.githubusercontent.com/36767434/163456020-e8a54dce-0a89-4025-82d3-b13d2f62b2d7.png)

Edit "Tasking Manager" text to read Public Domain Map Tasking Manager + OSM US logo

**Comment by jessbeutler** [comment]
@mvexel This might be a good jumping in point.

**Comment by quincylvania** [comment]
Superseded by integration of PDmap into the OSMUS tasking manager

**Comment by quincylvania** [comment]
See #8
