### ISSUE TITLE
TM won't build

### ISSUE THREAD

**Issue by mvexel** [publicdomainmap/tasking-manager#7]
Fails with 

```
cp: cannot stat 'node_modules/@hotosm/id/dist/*': No such file or directory
```

**Comment by mvexel** [comment]
`yarn start` yields

```
Failed to compile.

./src/components/editor.js
Module not found: Can't resolve 'iD' in '/home/mvexel/pdmap/tasking-manager/frontend/src/components'
Compiling...
```

**Comment by mvexel** [comment]
This line is (one of the) culprits: https://github.com/publicdomainmap/tasking-manager/blob/develop/frontend/src/components/editor.js#L4

**Comment by mvexel** [comment]
I tried renaming the `id` package we pull from our own fork on github to `id-editor` and change the appropriate references, but that didn't solve the problem completely.

**Comment by mvexel** [comment]
Haven't made any progress on this. @jimmyrocks any luck here? I can ask around in the iD dev community.

**Comment by quincylvania** [comment]
Superseded by #8. No need to built this repo anymore
